apps:
- name: "{{ cookiecutter.projectName }}"
  components:
    - name: "{{ cookiecutter.projectName }}"
      host: "{{ cookiecutter.repositoryProvider }}"
      repo: "{{ cookiecutter.repositoryOwner }}/{{ cookiecutter.repositoryName }}"
      path: templates/service-template.yaml